electron/clerk

README.md, src/index.ts
This addes a `notes: no-notes` option to codify the idiom Jeremy used in https://github.com/electron/electron/pull/14093
Introduces no new failures to `yarn test` so this should be G2G.
=> feat: add no-notes option

src/index.ts
This PR ensures that when users leave the default `Release Notes` section in PR templates on `electron/electron`, `clerk` fails to pass the check.
/cc @MarshallOfSound
=> fix: ensure users didn't leave PR template

README.md
Does what it says on the tin.
People often copypaste whatever's in the README and then tweak it for their own situation. This PR makes those README items follow better ptractices
=> docs: give examples of best practices

src/index.ts
I've noticed a few people typo'ing this with a space or an underscore, instead of insisting people spell it "correctly", let's just allow a few other ways of writing "no notes" 😄
=> chore: add more options for 'no-notes'

src/index.ts
Fixes an issue with markdown comments being persisted and messing with the release notes.
Before:
```js
{
"body": "**Release Notes Persisted**\n\n>  improved tray icon context menu and menu bar accessibility"
}
```
After: 
```js
{
"body": "**Release Notes Persisted**\n\n>  improved tray icon context menu and menu bar accessibility"
}
```
cc @ckerr
=> fix: remove any markdown comments from persisted notes

jest.config.js, package.json, src/__tests__/note.test.ts, src/constants.ts, src/index.ts, src/note-utils.ts, tsconfig.json, yarn.lock
Separates the network logic from the note parsing / comment generating logic so that the latter can be unit tested.
Adds some simple tests for detecting notes, generating notes & no-notes comments, and quoting single- and multiline notes
=> feat: add unit tests

src/__tests__/note.test.ts, src/index.ts, src/note-utils.ts
Fixes an issue surfaced in https://github.com/electron/electron/pull/25112#issuecomment-680465818.
More effectively checks for no-notes and also allows optional punctuation.
cc @nornagon @MarshallOfSound
=> fix: no-note matching with punctuation

src/__tests__/note.test.ts, src/note-utils.ts
Closes https://github.com/electron/clerk/issues/44.
Fixes an issue where we would call `notes.trim()` with a `notes` value of `null`, which throws.
cc @jkleinsc @MarshallOfSound @nornagon
=> fix: don't trim null notes

src/__tests__/note.test.ts, src/note-utils.ts
Refs https://github.com/electron/clerk/issues/44.
Fixes the regex for multiline notes to allow a bit more flexibility.
cc @jkleinsc @MarshallOfSound @nornagon
=> fix: multiline note format flexibility

src/__tests__/note.test.ts, src/note-utils.ts
Replace `<` and `>` with `&lt;` and `&gt;` to prevent a note from accidentally embedding live html. :smile_cat: 
CC @codebytere
=> fix: sanitize notes in case of embedded html

src/note-utils.ts
Another small fix for warnings found at [LGTM](https://lgtm.com/projects/g/electron/clerk/?mode=list).
Looks like it might have just been a tyop that transposed `$` and `` ` `` on these lines:
```
/^`no-notes.?$`/,
/^`no notes.?$`/,
```
Since `$` matches end-of-line, neither of these would ever hit since they were looking for a backtick after end-of-line.
=> fix:  bad regexes when matching no-notes variants

.github/workflows/lint.yml, .github/workflows/test.yml
Follow-up to #87, had a copy-and-paste error in the SHA for `actions/checkout` where the `v` prefix from the tag stuck around.
=> ci: fix SHA for actions/checkout

src/index.ts
Save the humans the effort of editing Dependabot PR bodies.
=> feat: set no notes in Dependabot PRs

src/index.ts
#110 worked as intended, but the `---` wasn't rendering correctly because it needs an additional newline before it.
=> chore: add another newline when editing Dependabot PRs

package.json, yarn.lock
I believe `@types/bunyan` was included by mistake in the past, and `debug` needs to be moved from `devDependencies` to `dependencies` because it's used in the runtime code.
=> build: cleanup deps

src/note-utils.ts, test/note.test.ts
Ref https://github.com/electron/electron/pull/44357
Fixes an issue where Clerk failed to find notes if `Notes:` was the first word present in the PR body.
=> fix: regex for multiline notes

package.json, src/note-utils.ts, tsconfig.json, yarn.lock
This PR:
- Bumps Node.js & dep to 20 to address a longstanding TODO
- Bumps up the sanitization of the default template to reduce unnecessary logging - previously there'd be a log for every time clerk found default notes.
=> refactor: bump node and modernize

src/index.ts, src/note-utils.ts, test/note.test.ts
Fixes the following no-notes explosion that could happen rarely:
The root cause of this was that when `build` PRs had no-notes added to them automatically, it was appended to the end of the existing PR body, even if the PR still had the default notes template. This then triggered a new PR edit webhook, and existing logic only checked for the first instance of `Notes:`, which would still be the default notes template, and thus it would try to append again, ad infinitum.
Fix this by editing the default notes template if it exists and appending `Notes: none` otherwise.
=> fix: no-notes explosion on some build PRs

package.json, yarn.lock
Bumping to clear the audit, and also drops some transitive dependencies which is nice.
=> chore: update probot to 13.4.3

package.json
yarn@v4 seems to deterministically run this, but on heroku sometimes `tsc` is not around. Leaves the `build` script that heroku will run at the right time
=> build: remove postinstall script
